config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'my_index', to: 'toppages#my_index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :ecos, except: [:index, :show]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/eco.rb
class Eco < ApplicationRecord
  validates :action, presence: true, length: { maximum: 255 }
  validates :co2, numericality: { only_integer: true, greater_than: 0, less_than: 5000 }
  
  belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :goal, length: { maximum: 100 }
  
  has_many :ecos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include SessionsHelper
    
  private
    
  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
  def counts(user)
    @count_ecos = user.ecos.count
  end
  
  def car_distance(x)
    if x >= 400
      @prace = '大阪'
    elsif x >= 300
      @prace = '琵琶湖'
    elsif x >= 200
      @prace = '愛知'
    elsif x >= 100
      @prace = '富士山'
    elsif x >= 50
      @prace = '相模原'
    elsif x >= 20
      @prace = '府中'
    else
      @prace = '都内'
    end
  end
end

app/controllers/ecos_controller.rb
class EcosController < ApplicationController
  before_action :require_user_logged_in, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def new
    @my_eco = Eco.new
  end
  
  def create
    if logged_in?
      @my_eco = current_user.ecos.build(eco_params)
    else
      @my_eco = Eco.new(eco_params)
    end
    
    if @my_eco.save
      flash[:success] = 'エコアクションが正常に投稿されました'
      redirect_to root_url
    else
      flash.now[:danger] = 'エコアクションが投稿されませんでした'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @my_eco.update(eco_params)
      flash[:success] = 'エコアクションは正常に更新されました'
      redirect_to root_url
    else
      flash.now[:danger] = 'エコアクションは更新されませんでした'
      render :edit
    end
  end
  
  def destroy
    @my_eco.destroy
    flash[:success] = 'アクションを削除しました'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def eco_params
    params.require(:eco).permit(:action, :co2)
  end
  
  def correct_user
    @my_eco = current_user.ecos.find_by(id: params[:id])
    unless @my_eco
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to root_url
  end
  
  private
  
  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  include ToppagesHelper
  
  before_action :require_user_logged_in, only: [:my_index]
  
  def index
    @ecos = Eco.order(id: :desc).page(params[:page]).per(15)
    @total_co2 = Eco.all.sum(:co2)
    @kiro = @total_co2 / 230
    car_distance(@kiro)
  end
  
  def my_index
    @my_ecos = current_user.ecos.order(id: :desc).page(params[:page])
    @my_total_co2 = @my_ecos.all.sum(:co2)
    @my_kiro = @my_total_co2 / 230
    if current_user.goal.present?
      @my_progress = (@my_kiro*100) / goal_to_kiro(current_user.goal)
    end
    counts(current_user)
    car_distance(@my_kiro) # my到達地点の格納
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :edit, :update]
  
  def show
    @my_ecos = current_user.ecos.order(id: :desc).page(params[:page]).per(15)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = 'ユーザを登録しました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました'
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if current_user.update(user_params)
      flash[:success] = '変更されました'
      redirect_to current_user
    else
      flash.now[:danger] = '変更されませんでした'
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :goal)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/toppages_helper.rb
module ToppagesHelper
  
  def goal_to_kiro(goal)
    if goal == '大阪'
      @kiro_goal = 400
    elsif goal == '琵琶湖'
      @kiro_goal = 300
    elsif goal == '愛知'
      @kiro_goal = 200
    elsif goal == '富士山'
      @kiro_goal = 100
    elsif goal == '相模原'
      @kiro_goal = 50
    else
      @kiro_goal = goal.to_i
    end
    return @kiro_goal
  end
  
end

app/views/ecos/_ecos.html.erb
<ul class='lest-group'>
  <% ecos.each do |eco| %>
    <li class='list-group-item' style= 'position: relative;'>
      <div>
        <% if eco.user.present? %>
          <%= eco.user.name %>
        <% else %>
          no name
        <% end %>
        <br>
        <%= eco.action %>
        <br>
        <%= eco.co2 %>グラム
      </div>
      
      <div style='position: absolute; top: 1px; right: 0px;'>
        <% if logged_in? && current_user == eco.user %>
          <div class="dropdown">
            <button type="button" class="btn btn-light dropdown-toggle" data-toggle="dropdown">
              <i class="fas fa-align-justify"></i>
            </button>
    
            <div class="dropdown-menu">
              <%= link_to '編集', edit_eco_path(eco), class: 'dropdown-item' %>
              <%= link_to '削除', eco, method: :delete, data: { confirm: 'You sure?' }, class: 'dropdown-item' %>
            </div>
          </div>
        <% end %>
      </div>
      
    </li>
  <% end %>
</ul>
  <%= paginate ecos %>

app/views/ecos/_form.html.erb
<div class='row mt-4'>
  <div class='col-lg-4 offset-lg-1'>
    <%= form_with(model: eco, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class='form-group'>
        <%= f.label :action, 'エコアクション' %>
        <%= f.text_field :action, class: 'form-control' %>
      </div>
      
      <div class='form-group'>
        <%= f.label :co2, 'CO2削減量' %>
        <%= f.number_field :co2, class: 'form-control' %>
      </div>
      
      <%= f.submit '投稿', class: 'btn btn-primary' %>
    <% end %>
  </div>
  
  <div class="col-lg-4">
    <table class="table table-striped table-bordered mt-3">
      <tr><th>参考アクション</th><th>参考CO2削減量</th></tr>
      <tr><td>1キロ車に乗らない</td><td>230g</td></tr>
      <tr><td>レジ袋1枚もらわない</td><td>60g</td></tr>
      <tr><td>ストーブ1°C下げる</td><td>1120g</td></tr>
      <tr><td>エアコン1°C上げる</td><td>80g</td></tr>
      <tr><td>アイドリングストップ5分</td><td>150g</td></tr>
      <tr><td>Eスタート(5秒で20キロまで加速)</td><td>530g</td></tr>
      <tr><td>1日トイレの蓋を閉める</td><td>70g</td></tr>
      <tr><td>お風呂の残り湯で1回洗濯</td><td>20g</td></tr>
    </table>
  </div>

</div>

app/views/ecos/edit.html.erb
<h1 >エコアクション編集ページ</h1>

<%= render 'form', eco: @my_eco %>

app/views/ecos/index.html.erb
<% if logged_in? %>
  <p>ログイン完了ユーザ: <%= current_user.name %></p>
  
  <%= link_to 'Logout', logout_path, method: :delete %>
  
  <%= form_with(model: @my_eco, local: true) do |f| %>
    <%= f.text_field :action %>
    <%= f.number_field :co2 %>
    <%= f.submit 'Post' %>
  <% end %>
  
  <h1>マイエコアクション一覧</h1>
  
  <%= render 'ecos', ecos: @my_ecos %>
<% else %>
  <%= link_to 'Sign up now!', signup_path %>
  <%= link_to 'Sign in', login_path %>
<% end %>


<h1>エコアクション一覧</h1>

<h2><%= @total_co2 %></h2>
<h2><%= @kiro %>キロ走行</h2>
<h2><%= car_distance( @kiro ) %></h2>

<%= render 'ecos', ecos: @ecos %>

<%= link_to '新規エコアクションの投稿', new_eco_path %>

app/views/ecos/new.html.erb
<h1>エコアクション新規作成ページ</h1>

<%= render 'form', eco: @my_eco %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id='error_explanation' class='alert alert-warning'>
    <ul class='mb-0'>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class='alert alert-<%= message_type %>'><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class='mb-0'>
  <nav class='navbar navbar-expand-sm navbar-light pt-4 pb-4' id='top_nav'>
    <a class='navbar-brand' href='/'>EcoShow</a>
    <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent'>
      <span class='navbar-toggler-icon'></span>
    </button>
    
    <div class='collapse navbar-collapse justify-content-end' id='navbarSupportedContent'>
      <ul class='navbar-nav'>
        <% if logged_in? %>
          <li class='nav-item'><%= link_to '新規エコアクションの投稿', new_eco_path, class: 'btn btn-outline-primary' %></li>
          <li class='nav-item dropdown'>
            <a href='#' class='nav-link dropdown-toggle' data-toggle='dropdown'><%= current_user.name %></a>
            <ul class='dropdown-menu dropdown-menu-right'>
              <li class='dropdown-item'><%= link_to 'My profile', user_path(current_user) %></li>
              <li class='dropdown-divider'></li>
              <li class='dropdown-item'><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class='nav-item'><%= link_to 'ログインせずにエコアクションを投稿', new_eco_path, class: 'btn btn-outline-primary' %></li>
          <li class='nav-item'><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class='nav-item'></li><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>EcoShow</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class='container-fluid'>
      <%= render 'layouts/flash_messages' %>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/toppages/index.html.erb
<div class='catch'>
  <img src="/assets/都内.jpg" alt="風車」の画像">
  <div class='letter'>
    みんなの記録<br>
    CO2:<%= @total_co2 %>グラム<br>
    走行距離:<%= @kiro %>キロ&gt;<%= @prace %>
  </div>
</div>

<div class='row'>
  <div class='col-md-6 offset-md-3'>
    <ul class='nav nav-tabs nav-justified mb-3'>
      <% if logged_in? %>
      
        <li class='nav-item'><a href="<%= my_index_path %>" class="nav-link <%= 'active' if current_page?(my_index_path) %>">MYエコアクション<span class="badge badge-secondary"><%= @count_ecos %></span></a></li>
      
      <% end %>
      
      <li class="nav-item"><a href="<%= root_path %>" class="nav-link <%= 'active' if current_page?(root_path) %>">総エコアクション</a></li>
       
    </ul>
    
    <%= render 'ecos/ecos', ecos: @ecos %>
    
  </div>
</div>

app/views/toppages/my_index.html.erb
<div class='catch'>
  <img src="/assets/<%= @prace %>.jpg" alt="<%= @prace %>の画像">
  <div class='letter'>
    自分の記録<br>
    CO2:<%= @my_total_co2 %>グラム<br>
    走行距離:<%= @my_kiro %>キロ&gt;<%= @prace %>
    
    <% if current_user.goal.present? %>
      <br>
      <% if @my_kiro >= goal_to_kiro(current_user.goal) %>
        <span style='color:red'>おめでとう目標達成！</span><br>
      <% else %>
        目標:<%= current_user.goal %><br>
      <% end %>
        
      <div class="progress">
        <div class="progress-bar progress-bar-striped" role="progressbar" style="width: <%= @my_progress %>%" aria-valuenow="<%= @my_progress %>" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
    <% end %>
      
  </div>
</div>

<div class='row'>
  <div class='col-md-6 offset-md-3'>
    
    <ul class='nav nav-tabs nav-justified mb-3'>
      <li class='nav-item'><a href="<%= my_index_path %>" class="nav-link <%= 'active' if current_page?(my_index_path) %>">MYエコアクション<span class="badge badge-secondary"><%= @count_ecos %></span></a></li>
      <li class="nav-item"><a href="<%= root_path %>" class="nav-link <%= 'active' if current_page?(root_path) %>">総エコアクション</a></li>
     </ul>
    <%= render 'ecos/ecos', ecos: @my_ecos %>
  
  </div>
</div>

app/views/users/edit.html.erb
<div class='row'>
  <div class='col-sm-6 offset-sm-3'>
    
    <%= form_with(model: current_user, local: true) do |f| %>
    
    <%= render 'layouts/error_messages', model: f.object %>
  
      <div class='form-group'>
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class='form-group'>
        <%= f.label :email, 'Email' %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      
      <div class='form-group'>
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class='form-group'>
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      
      <div class='form-group'>
          <%=f.label :goal, '目標' %>
          <%= f.select :goal, [["大阪(難易度5)", "大阪"], ["琵琶湖(難易度4)", "琵琶湖"], ["愛知(難易度3)", "愛知"], ["富士山(難易度2)", "富士山"], ["相模原(難易度1)", "相模原"]], include_blank: "新宿がスタート", class: 'form-control' %>
      </div>
  
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
      
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class='text-center'>
  <h1>Signup</h1>
</div>

<div class='row'>
  <div class='col-sm-6 offset-sm-3'>
    
    <%= form_with(model: @user, local: true) do |f| %>
    
    <%= render 'layouts/error_messages', model: f.object %>
  
      <div class='form-group'>
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      
      <div class='form-group'>
        <%= f.label :email, 'Email' %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      
      <div class='form-group'>
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      
      <div class='form-group'>
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
  
      <%= f.submit 'signup', class: 'btn btn-primary btn-block' %>
      
    <% end %>
  </div>
</div>

<p style='text-align: center;' class= 'mt-4'>already have? <%= link_to 'Log in', login_path %></p>
  

app/views/users/show.html.erb
<div class='row'>

  <div class='col-md-4 offset-md-2'>
  
    <h1><%= current_user.name %>  <%= link_to 'ユーザ情報を編集する', edit_user_path(current_user), class: 'btn btn-outline-danger' %></h1>
    
    <%= form_with(model: current_user, local: true) do |f| %>
        
      <%= render 'layouts/error_messages', model: f.object %>
          
      <div class='form-group'>
        <%=f.label :goal, '目標' %>
        <%= f.select :goal, [["大阪(難易度5)", "大阪"], ["琵琶湖(難易度4)", "琵琶湖"], ["愛知(難易度3)", "愛知"], ["富士山(難易度2)", "富士山"], ["相模原(難易度1)", "相模原"]], include_blank: "新宿がスタート", class: "form-control" %>
        <%= f.submit '登録', class: 'btn btn-outline-primary' %>
      </div>
          
    <% end %>
    
  </div>
  
  <div class='col-md-4'>
    <%= render 'ecos/ecos', ecos: @my_ecos %>
  </div>
  
</div>